# Generated by Django 5.2.5 on 2025-12-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='pergunta',
            field=models.TextField(),
        ),
    ]
