# Generated by Django 5.2.5 on 2025-12-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
