# Generated by Django 5.2.5 on 2026-01-12 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_artigo_ativo_alter_artigo_avaliacoes_negativas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Chamado')),
                ('cliente', models.CharField(max_length=150, verbose_name='Nome do Cliente/Prefeitura')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('prioridade', models.CharField(choices=[('baixo', '🟢 Baixa'), ('medio', '🟡 Média'), ('alto', '🔴 Alta')], default='medio', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_progresso', 'Em Andamento'), ('aguardando', 'Aguardando'), ('fechado', 'Concluído')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'db_table': 'menu_chamado',
            },
        ),
        migrations.CreateModel(
            name='InteracaoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
            ],
            options={
                'verbose_name': 'Interação',
                'verbose_name_plural': 'Interações',
                'db_table': 'menu_interacao_chamado',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacaoartigo',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='artigo',
            name='menu_artigo_ativo_aed728_idx',
        ),
        migrations.RemoveIndex(
            model_name='artigo',
            name='menu_artigo_categor_4fc285_idx',
        ),
        migrations.AlterField(
            model_name='artigo',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='tipo',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('guia', 'Guia'), ('faq', 'FAQ')], default='tutorial', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='avaliacaoartigo',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_detalhadas', to='menu.artigo'),
        ),
        migrations.AlterField(
            model_name='avaliacaoartigo',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='avaliacaoartigo',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='avaliacaoartigo',
            name='session_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avaliacaoartigo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos_menu', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável'),
        ),
        migrations.AddField(
            model_name='interacaochamado',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='menu.chamado', verbose_name='Chamado'),
        ),
        migrations.AddField(
            model_name='interacaochamado',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
    ]
