# Generated by Django 5.2.5 on 2026-01-12 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_chamado_interacaochamado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Mensagem')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='chamados/anexos/', verbose_name='Arquivo Anexo')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('is_suporte', models.BooleanField(default=False, verbose_name='É Suporte?')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='menu.chamado', verbose_name='Chamado')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'db_table': 'menu_mensagem',
                'ordering': ['data_envio'],
            },
        ),
        migrations.DeleteModel(
            name='InteracaoChamado',
        ),
    ]
