# Generated by Django 5.2.5 on 2026-01-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_mensagem_delete_interacaochamado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meus_chamados_menu', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_progresso', 'Em Andamento'), ('aguardando', 'Aguardando'), ('fechado', 'Concluído')], db_index=True, default='aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Envio'),
        ),
    ]
