# Generated by Django 5.2.5 on 2025-11-12 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('data', 'Data'), ('select', 'Seleção'), ('checkbox', 'Checkbox')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('opcoes', models.TextField(blank=True, help_text='Para campos de seleção, separar opções por vírgula')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campo Personalizado',
                'verbose_name_plural': 'Campos Personalizados',
            },
        ),
        migrations.CreateModel(
            name='CategoriaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de Ticket',
                'verbose_name_plural': 'Categorias de Tickets',
            },
        ),
        migrations.CreateModel(
            name='StatusTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#007bff', max_length=7)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Status do Ticket',
                'verbose_name_plural': 'Status dos Tickets',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='UrgenciaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nivel', models.IntegerField(unique=True)),
                ('cor', models.CharField(default='#6c757d', max_length=7)),
                ('tempo_resposta_esperado', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nível de Urgência',
                'verbose_name_plural': 'Níveis de Urgência',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('data_limite', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('incidente', 'Incidente'), ('problema', 'Problema'), ('solicitacao', 'Solicitação de Serviço')], default='incidente', max_length=20)),
                ('numero_ticket', models.CharField(editable=False, max_length=20, unique=True)),
                ('atribuido_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.categoriaticket')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_criados', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.statusticket')),
                ('urgencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.urgenciaticket')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='InteracaoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('comentario', 'Comentário'), ('atualizacao', 'Atualização'), ('solucao', 'Solução')], default='comentario', max_length=20)),
                ('interno', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Interação do Ticket',
                'verbose_name_plural': 'Interações dos Tickets',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'urgencia'], name='tickets_tic_status__a71dde_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['data_criacao'], name='tickets_tic_data_cr_09e150_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['criado_por', 'status'], name='tickets_tic_criado__29b1b6_idx'),
        ),
    ]
