# Generated by Django 5.2.5 on 2025-11-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ativos_relacionados',
            field=models.ManyToManyField(blank=True, related_name='tickets_relacionados', to='ativos.ativo', verbose_name='Ativos Relacionados'),
        ),
    ]
