# Generated by Django 5.2.5 on 2025-11-13 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True)),
                ('fornecedor', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('renovacao_automatica', models.BooleanField(default=False)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='contratos/')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('suporte_email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='TipoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Ativo',
                'verbose_name_plural': 'Tipos de Ativo',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField(blank=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_patrimonio', models.CharField(max_length=50, unique=True, verbose_name='Tag Patrimônio')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Série')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('operacional', 'Operacional'), ('manutencao', 'Em Manutenção'), ('desativado', 'Desativado'), ('reserva', 'Reserva')], default='operacional', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('data_garantia', models.DateField(blank=True, null=True, verbose_name='Fim da Garantia')),
                ('especificacoes', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ativos_alocados', to=settings.AUTH_USER_MODEL)),
                ('fabricante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ativos.fabricante')),
                ('localizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ativos.localizacao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ativos.tipoativo')),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('versao', models.CharField(max_length=50)),
                ('tipo_licenca', models.CharField(choices=[('volume', 'Licença por Volume'), ('oem', 'OEM'), ('subscription', 'Assinatura'), ('gratuito', 'Gratuito')], max_length=20)),
                ('chave_licenca', models.CharField(blank=True, max_length=200)),
                ('total_licencas', models.IntegerField(default=1)),
                ('licencas_utilizadas', models.IntegerField(default=0)),
                ('data_expiracao', models.DateField(blank=True, null=True)),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.fabricante')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
        migrations.CreateModel(
            name='ContratoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.ativo')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.contrato')),
            ],
            options={
                'verbose_name': 'Contrato do Ativo',
                'verbose_name_plural': 'Contratos dos Ativos',
                'unique_together': {('contrato', 'ativo')},
            },
        ),
        migrations.CreateModel(
            name='InstalacaoSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_instalacao', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.ativo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ativos.software')),
            ],
            options={
                'verbose_name': 'Instalação de Software',
                'verbose_name_plural': 'Instalações de Software',
                'unique_together': {('software', 'ativo')},
            },
        ),
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['tag_patrimonio'], name='ativos_ativ_tag_pat_ccf298_idx'),
        ),
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['tipo', 'estado'], name='ativos_ativ_tipo_id_bad134_idx'),
        ),
        migrations.AddIndex(
            model_name='ativo',
            index=models.Index(fields=['usuario_final'], name='ativos_ativ_usuario_96a83a_idx'),
        ),
    ]
